-- schema.sql: create user/schema and tables for HR app
-- Run as SYSTEM or connect as SYSTEM and then run the statements to create hr_app

CREATE USER hr_app IDENTIFIED BY hr_password;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO hr_app;
ALTER USER hr_app QUOTA UNLIMITED ON USERS;

-- The script is normally run as SYSTEM. Create application objects in HR_APP,
-- not in SYSTEM, before running the statements below.
ALTER SESSION SET CURRENT_SCHEMA = hr_app;

-- Tables
CREATE TABLE departments (
  dept_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  location VARCHAR2(100)
);

CREATE TABLE employees (
  emp_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  first_name VARCHAR2(50) NOT NULL,
  last_name VARCHAR2(50) NOT NULL,
  email VARCHAR2(100) UNIQUE NOT NULL,
  hire_date DATE DEFAULT SYSDATE,
  dept_id NUMBER REFERENCES departments(dept_id),
  salary NUMBER(12,2) NOT NULL,
  salary_grade VARCHAR2(10)
);

CREATE TABLE attendance (
  att_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  emp_id NUMBER REFERENCES employees(emp_id),
  work_date DATE NOT NULL,
  hours_worked NUMBER(4,2) DEFAULT 8
);

CREATE TABLE payrolls (
  payroll_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  emp_id NUMBER REFERENCES employees(emp_id),
  payroll_month VARCHAR2(7) NOT NULL,
  gross_pay NUMBER(12,2),
  tax NUMBER(12,2),
  deductions NUMBER(12,2),
  net_pay NUMBER(12,2),
  processed_date DATE DEFAULT SYSDATE
);

CREATE SEQUENCE seq_payroll START WITH 1 INCREMENT BY 1;

CREATE VIEW vw_department_payroll AS
SELECT d.dept_id, d.name AS dept_name, SUM(p.net_pay) AS total_net_pay
FROM departments d
JOIN employees e ON e.dept_id = d.dept_id
JOIN payrolls p ON p.emp_id = e.emp_id
GROUP BY d.dept_id, d.name;
